// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type SearchRequest struct {
	OrderID uint64 `path:"orderID"`
}

type SearchResponse struct {
	OrderID  uint64 `json":"orderID"`
	Status   int    `json:"status"`
	Username string `json:"username"`
}
