// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type DetailRequest struct {
	UserID int64 `path:"user_id"`
}

type DetailResponse struct {
	Username string `json:"username"`
	Gender   int64  `json:"gender"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Message      string `json:"message"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int    `json:"accessExpire"`
	RefreshAfter int    `json:"refreshAfter"`
}

type SignupRequest struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
	Gender     int64  `json:"gender,options=0|1|2,default=2"`
}

type SignupResponse struct {
	Message string `json:"message"`
}
